model:
  boosting_type: gbdt
  objective: regression
  metric: mae

  device_type: gpu
  gpu_platform_id: 0
  gpu_device_id: 0
  gpu_use_dp: false

  num_leaves: 512
  max_depth: -1
  max_bin: 511

  learning_rate: 0.02
  n_estimators: 2500

  feature_fraction: 0.9
  bagging_fraction: 0.9
  bagging_freq: 1

  min_data_in_leaf: 60
  min_sum_hessian_in_leaf: 1e-3

  lambda_l1: 0.0
  lambda_l2: 3.0
  min_gain_to_split: 0.0

  verbosity: -1
