model:
  boosting_type: gbdt
  objective: regression
  metric: mae

  device_type: gpu
  gpu_platform_id: 0
  gpu_device_id: 0
  gpu_use_dp: false

  num_leaves: 128
  max_depth: -1
  max_bin: 255

  learning_rate: 0.05
  n_estimators: 1500

  feature_fraction: 0.7
  bagging_fraction: 0.7
  bagging_freq: 1

  min_data_in_leaf: 150
  min_sum_hessian_in_leaf: 1e-3

  lambda_l1: 0.0
  lambda_l2: 5.0
  min_gain_to_split: 0.0

  verbosity: -1
