lightgbm:
  boosting_type: "gbdt"
  n_estimators: 1200
  learning_rate: 0.01
  num_leaves: 63
  feature_fraction: 0.8
  bagging_fraction: 0.8
  reg_alpha: 1.0
  reg_lambda: 1.0
  metric: "rmse"

ridge:
  alpha: 1.0

mlp:
  layers: [256,128,64]
  alpha: 1e-5
  learning_rate_init: 1e-3
  max_iter: 30

stacker:
  alpha: 0.5
