model:
  boosting_type: gbdt
  objective: regression
  metric: mae
  device_type: gpu
  gpu_platform_id: 0
  gpu_device_id: 0
  max_depth: -1
  min_sum_hessian_in_leaf: 0.001
  lambda_l1: 0.0
  lambda_l2: 5.0
  min_gain_to_split: 0.0
  verbosity: -1
  bagging_freq: 1
  max_bin: 511
  learning_rate: 0.03
  num_leaves: 256
  min_data_in_leaf: 100
  bagging_fraction: 0.8
  n_estimators: 2000
  feature_fraction: 0.8
