device: gpu
gpu_platform_id: 0
gpu_device_id: 0

task: train
objective: regression
metric: rmse
boosting_type: gbdt

learning_rate: 0.01
n_estimators: 4000

num_leaves: 1024
max_depth: -1
max_bin: 255

feature_fraction: 0.80
bagging_fraction: 0.80
bagging_freq: 1

min_data_in_leaf: 50

lambda_l1: 1.0
lambda_l2: 5.0

verbosity: -1
