general:
  row_limit: 150000        # 50k = trop faible pour un modèle fiable
  n_folds: 5               # 2-fold = mauvais CV → variance énorme
  shuffle: true            # indispensable
  stratify: false          # pas utile en regression Numerai

files:
  train: "data/numerai_training_data.parquet"
  tournament: "data/numerai_tournament_data.parquet"
  submission: "submission.csv"

seed: 42
