general:
  row_limit: 200000
  n_folds: 5
  shuffle: true
  stratify: false
  fold_type: "kfold"
  verbose: false


files:
  train: "data/numerai_training_data.parquet"
  tournament: "data/numerai_tournament_data.parquet"
  submission: "submission.csv"

seed: 42
